use std::fmt::Write;

use anyhow::{Result, bail};

pub const NEC_LEADER_MIN_US: u32 = 8_000;
pub const NEC_LEADER_MAX_US: u32 = 10_000;
pub const NEC_ZERO_MAX_US: u32 = 1_000;
pub const NEC_BIT_MAX_US: u32 = 2_500;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Pulse {
    pub high: bool,
    pub duration_us: u32,
}

pub fn decode_nec(pulses: &[Pulse]) -> Result<Vec<u8>> {
    let leader = pulses
        .first()
        .ok_or_else(|| anyhow::anyhow!("NEC pulse sequence is empty"))?;
    if !(NEC_LEADER_MIN_US..=NEC_LEADER_MAX_US).contains(&leader.duration_us) {
        bail!(
            "NEC leader is {} us; expected {}..={} us",
            leader.duration_us,
            NEC_LEADER_MIN_US,
            NEC_LEADER_MAX_US
        );
    }
    let bits = pulses
        .iter()
        .skip(1)
        .filter(|pulse| !pulse.high && pulse.duration_us <= NEC_BIT_MAX_US)
        .map(|pulse| u8::from(pulse.duration_us > NEC_ZERO_MAX_US))
        .collect::<Vec<_>>();
    if bits.len() < 32 || bits.len() % 8 != 0 {
        bail!(
            "NEC sequence decoded to {} bits; expected at least 32 and a multiple of 8",
            bits.len()
        );
    }
    Ok(bits
        .chunks(8)
        .map(|chunk| chunk.iter().fold(0_u8, |byte, bit| (byte << 1) | bit))
        .collect())
}

pub fn parse_hex_code(value: &str) -> Result<[u8; 4]> {
    let value = value.trim().trim_start_matches("0x");
    if value.len() != 8 || !value.chars().all(|character| character.is_ascii_hexdigit()) {
        bail!("IR code must contain exactly 8 hexadecimal digits");
    }
    let mut output = [0_u8; 4];
    for (index, byte) in output.iter_mut().enumerate() {
        *byte = u8::from_str_radix(&value[index * 2..index * 2 + 2], 16)?;
    }
    Ok(output)
}

pub fn lirc_config(codes: &[(String, [u8; 4])]) -> String {
    let mut output = String::from(
        "# Generated by argon40ctl\n# NEC configuration for Argon40\n\nbegin remote\n  name argon\n  bits 32\n  flags SPACE_ENC\n  eps 20\n  aeps 200\n  header 8800 4400\n  one 550 1650\n  zero 550 550\n  ptrail 550\n  repeat 8800 2200\n  gap 38500\n  toggle_bit 0\n  frequency 38000\n  begin codes\n",
    );
    for (name, code) in codes {
        let normalized = name.trim().to_ascii_uppercase();
        let _ = writeln!(
            output,
            "    KEY_{normalized} 0x{:02x}{:02x}{:02x}{:02x}",
            code[0], code[1], code[2], code[3]
        );
    }
    output.push_str("  end codes\nend remote\n");
    output
}

pub const DEFAULT_REMOTE: &[(&str, [u8; 4])] = &[
    ("POWER", [0x00, 0xff, 0x39, 0xc6]),
    ("UP", [0x00, 0xff, 0x53, 0xac]),
    ("DOWN", [0x00, 0xff, 0x4b, 0xb4]),
    ("LEFT", [0x00, 0xff, 0x99, 0x66]),
    ("RIGHT", [0x00, 0xff, 0x83, 0x7c]),
    ("VOLUMEUP", [0x00, 0xff, 0x01, 0xfe]),
    ("VOLUMEDOWN", [0x00, 0xff, 0x81, 0x7e]),
    ("OK", [0x00, 0xff, 0x73, 0x8c]),
    ("HOME", [0x00, 0xff, 0xd3, 0x2c]),
    ("MENU", [0x00, 0xff, 0xb9, 0x46]),
    ("BACK", [0x00, 0xff, 0x09, 0xf6]),
];

#[cfg(test)]
mod tests {
    use super::*;

    fn pulses_for(code: [u8; 4]) -> Vec<Pulse> {
        let mut pulses = vec![
            Pulse {
                high: true,
                duration_us: 9_000,
            },
            Pulse {
                high: false,
                duration_us: 4_500,
            },
        ];
        for byte in code {
            for shift in (0..8).rev() {
                pulses.push(Pulse {
                    high: true,
                    duration_us: 550,
                });
                pulses.push(Pulse {
                    high: false,
                    duration_us: if byte & (1 << shift) == 0 { 550 } else { 1_650 },
                });
            }
        }
        pulses
    }

    #[test]
    fn decodes_legacy_nec_bit_order() {
        let expected = [0x00, 0xff, 0x39, 0xc6];
        assert_eq!(decode_nec(&pulses_for(expected)).unwrap(), expected);
    }

    #[test]
    fn menu_and_back_are_distinct_regression() {
        assert_eq!(DEFAULT_REMOTE[9].0, "MENU");
        assert_eq!(DEFAULT_REMOTE[10].0, "BACK");
        let config = lirc_config(
            &DEFAULT_REMOTE
                .iter()
                .map(|(name, code)| ((*name).to_owned(), *code))
                .collect::<Vec<_>>(),
        );
        assert!(config.contains("KEY_MENU"));
        assert!(config.contains("KEY_BACK"));
        assert!(!config.contains("KEY_MENUBACK"));
    }
}
